### PR TITLE
Haha. And you call yourself a "PHP Professor" ;)

### PR DESCRIPTION
**Pull request by applqpak**

### CODE REVIEW

**Comment by Taki21** [comment]
Who said i was a professor?! sorry i think u misheard dat xD

**Comment by applqpak** [comment]
No, I didn't.

**Comment by Taki21** [comment]
Lol

**Comment by Gamecrafter** [comment]
@applqpak You don't need to `implement Plugin`. `PluginBase` already does so.

**Comment by remotevase** [comment]
true, but there's no harm in doing so

**Comment by Taki21** [comment]
Hey I am a Professor xD @applqpak was right lol

**Pull request merged**
